<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>M.S. Technosoft Private Limited - Bill Management</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            background-image: url('https://wallpapercave.com/wp/wp2844990.jpg'); /* Replace with your background image */
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        
        .header {
            background-color: rgba(0, 0, 0, 0.7);
            color: white;
            padding: 20px;
            text-align: center;
        }
        
        .header input {
            width: 100px;
            text-align: center;
        }
        
        .container {
            margin: 20px;
            background-color: orange;
            padding: 20px;
            border-radius: 10px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        th, td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        
        th {
            background-color: #f2f2f2;
        }
        
        select {
            padding: 5px;
        }
        
        form {
            margin-top: 20px;
        }
        
        form label, form input, form select {
            display: block;
            margin-bottom: 10px;
        }
        
        .delete-btn {
            background-color: #ff0000;
            color: #fff;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>M.S. Technosoft Private Limited</h1>
        <div>
            <label for="billsRaised">Bills Raised:</label>
            <input type="text" id="billsRaised" value="45,28,705">
            
            <label for="billsPassed">Bills Passed:</label>
            <input type="text" id="billsPassed" value="21,45,388">
            
            <label for="pendingBills">Pending Bills:</label>
            <input type="text" id="pendingBills" value="23,83,317">
            
            <label for="billsToBeMade">Bills to be Made:</label>
            <input type="text" id="billsToBeMade" value="3,85,212">
        </div>
    </div>
    
    <div class="container">
        <h2>Add Bill</h2>
        <form id="billForm">
            <label for="description">Description:</label>
            <input type="text" id="description" required="">
            
            <label for="date">Date:</label>
            <input type="date" id="date" required="">
            
            <label for="amount">Amount (INR):</label>
            <input type="number" id="amount" required="">
            
            <label for="category">Category:</label>
            <select id="category">
                <option value="raised">Raised</option>
                <option value="passed">Passed</option>
                <option value="notRaised" selected="selected">Not Raised</option>
            </select>
            
            <button type="button" onclick="addBill()">Add Bill</button>
        </form>
        
        <h2>Bills</h2>
        <table>
            <tbody><tr>
                <th>Serial No.</th>
                <th>Description</th>
                <th>Date</th>
                <th>Amount (INR)</th>
                <th>Category</th>
                <th>Action</th>
            </tr>
            </tbody><tbody id="billList">
                <!-- Populated dynamically using JavaScript -->
            <tr>
                <td>1</td>
                <td>Manglam Imaging</td>
                <td>2023-03-28</td>
                <td>512344.00</td>
                <td>passed</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>2</td>
                <td>Manglam Extraction</td>
                <td>2023-03-29</td>
                <td>442500.00</td>
                <td>passed</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>3</td>
                <td>Manglam Analysis</td>
                <td>2023-05-22</td>
                <td>528307.00</td>
                <td>raised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>5</td>
                <td>Manglam Analysis - 3 </td>
                <td>2023-03-25</td>
                <td>679014.00</td>
                <td>passed</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>6</td>
                <td>Ganganagar Imaging</td>
                <td>2023-03-28</td>
                <td>69030.00</td>
                <td>passed</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>7</td>
                <td>Ganganagar Extraction</td>
                <td>2023-03-29</td>
                <td>442500.00</td>
                <td>passed</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>8</td>
                <td>Ganganagar Analysis</td>
                <td>2023-05-22</td>
                <td>819200.00</td>
                <td>raised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>9</td>
                <td>Highway king Imaging</td>
                <td>2023-08-10</td>
                <td>58149.00</td>
                <td>notRaised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>10</td>
                <td>Mumbai Imaging</td>
                <td>2023-08-10</td>
                <td>191160.00</td>
                <td>notRaised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>11</td>
                <td>Ajmer Imaging</td>
                <td>2023-04-11</td>
                <td>106200.00</td>
                <td>raised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>12</td>
                <td>Ajmer Extraction</td>
                <td>2023-04-11</td>
                <td>380550.00</td>
                <td>raised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>13</td>
                <td>Ajmer Analysis</td>
                <td>2023-05-17</td>
                <td>278907.00</td>
                <td>raised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr><tr>
                <td>13</td>
                <td>Manglam Analysis</td>
                <td>2023-08-10</td>
                <td>135894.00</td>
                <td>notRaised</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            </tr></tbody>
        </table>
    </div>
    
    <script>
        const billList = document.getElementById('billList');
        const billForm = document.getElementById('billForm');
        
        function addBill() {
            const descriptionInput = document.getElementById('description');
            const dateInput = document.getElementById('date');
            const amountInput = document.getElementById('amount');
            const categorySelect = document.getElementById('category');
            
            const description = descriptionInput.value;
            const date = dateInput.value;
            const amount = parseFloat(amountInput.value);
            const category = categorySelect.value;
            
            if (description === '' || isNaN(amount)) {
                alert('Please enter valid bill details.');
                return;
            }
            
            const newRow = document.createElement('tr');
            newRow.innerHTML = `
                <td>${billList.children.length + 1}</td>
                <td>${description}</td>
                <td>${date}</td>
                <td>${amount.toFixed(2)}</td>
                <td>${category}</td>
                <td><button class="delete-btn" onclick="deleteBill(this)">Delete</button></td>
            `;
            
            billList.appendChild(newRow);
            
            descriptionInput.value = '';
            dateInput.value = '';
            amountInput.value = '';
        }

        function deleteBill(button) {
            const row = button.parentNode.parentNode;
            billList.removeChild(row);
        }
    </script>


</body></html>
